title: WCA Software
description: A collection of documentation and guides for development of the WCA's software ecosystem.
theme: just-the-docs

url: https://thewca.github.io
favicon_ico: /assets/images/favicon.ico
color_scheme: dark

aux_links:
  WCA Main Repo: https://github.com/thewca/worldcubeassociation.org

nav_external_links:
  - title: Unofficial API 
    url: https://wca-rest-api.robiningelbrecht.be/


callouts:
  warning:
    title: Warning
    color: red
  info:
    title: Info
    color: blue
  help:
    title: Help Wanted
    color: yellow
